controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
utilisateur_accueil:
    path: /Utilisateur/Accueil
    controller: App\Controller\RedirectionController